### ISSUE TITLE
Team-70-Terriers

### ISSUE THREAD

**Issue by RamseyNjire** [RamseyNjire/old-apple-site-clone#2]
#Overly specific class names
#No-repeat for images
#Try more colors for gradient
#great work!

**Comment by s0kil** [comment]
![Screenshot_2020-02-25 Apple](https://user-images.githubusercontent.com/24403355/75257329-ccccf200-57b2-11ea-9468-7c0ad528ab7d.jpg)

**Comment by RamseyNjire** [comment]
Fixed all the changes!
